#!/bin/bash

cat << EOF > /tmp/minecraftedu-server/settings/serverwizardsettings.ini
# Generated by docker on $(date)
# Settings for MinecraftEdu Server Launcher and MinecraftEdu Server. Most of these settings can be changed through MinecraftEdu Server Launcher settings menu or through MinecraftEdu Server.

# Parameters how Server is being launched through the Server Launcher.
launch-parameters=%JAVAEXEC% %PERFORMANCEPARAMS% -Xmx%RAM%M -Xms%RAM%M -jar %SERVERTYPE%_server.jar

# Used by Server Launcher to determine path to launched world. Do not modify manually.
level-name=

# When student is joining, should we also check that the user's alias is already known in the server. Any new users could then not join the server if enabled. Links to alias-protection setting. Default: false
restrict-new-users-to-join=$RESTRICT_NEW_USERS

# Should we kick players who are idle for certain time in the server. Default: false
kick-idle-players=$KICK_IDLE_PLAYERS

# Used by Server Launcher to determine
saved-map-name=$SAVED_MAP_NAME

# Should we also kick idle ops (teachers) out from the server. Default: false
kick-idle-ops=$KICK_IDLE_OPS

# Server Launcher and Server language. Set from the application, do not modify. Default: en_US
language=$SERVER_LANGUAGE

# Should we log a entry in server log file if a player is idle. Default: false
log-idle-players=false

# If you want to show custom IP address in the server's top menu, define it here. Will not be used anywhere else. If empty, will automatically get the IP address. Default: empty
server-ip=

# If true, user data is being stored in the server using usernames. Otherwise with user aliases. Default: false
store-players-with-alias=$STORE_PLAYERS_WITH_ALIAS

# What server will be launched using the Server Launcher. Can be minecraftedu, minecraft or custom. Default: minecraftedu
server-type=minecraftedu

version=1.71

# If true, all console messages will be written in minecraftedu/debug folder. Default: true
writedebuglogtofile=$WRITE_DEBUG_LOG_TO_FILE

# If you want to store your minecraftedu world saves to custom location, you can set path to that folder here. Default: empty
overrided-saved-worlds-folder=

# Should we take backups of the worlds launched using the Server Launcher in folder servertool/worlds/backups. Default: true
take-backups=$TAKE_BACKUPS

# When students are joining the server, should they have the possibility to password protect their aliases. Default: false
alias-protection=$ALIAS_PROTECTION

# Server teacher password in MD5 encrypted format. If you wish to manually set this, you can use any web service to generate MD5 hash from your text and type it here.
password=$(echo -n "$TEACHER_PASSWORD" | md5sum | cut -c 1-32)

# How long was the teacher password. Only shown to user when he is changing the current teacher password.
password-length=$(echo -n "$TEACHER_PASSWORD" | wc -c)

# Used by Server Launcher to
loaded-saved-map=$LOADED_SAVED_MAP

# First character of teacher password. Only shown to user when he is changing the current teacher password.
password-first-character=$(echo -n "$TEACHER_PASSWORD" | cut -c 1)

# Time (in minutes) how long user needs to be idle before he is kicked from the server. Default: 5
kick-idle-players-interval=$kick-idle-players-interval

# How much RAM memory in megabytes (MB) will be assigned for the Server. Default: 1024
ram=$MINECRAFT_MEM
EOF
